import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { RenderPlan } from "@vf/vdsl";
import { resolveImageSources } from "./render.js";

const rendererFile = fileURLToPath(import.meta.url);
const rendererDir = path.dirname(rendererFile);
const ext = rendererFile.endsWith(".ts") ? "tsx" : "js";
const rootSrcPath = `${rendererDir}/Root.${ext}`;

export interface StudioWorkspace {
  /** The @remotion/cli binary to spawn (`remotion studio`). */
  bin: string;
  /** Directory to run the CLI in (the generated mini remotion project). */
  cwd: string;
  workspaceDir: string;
}

const studioEntryTemplate = (renderPlan: RenderPlan): string => `import { Composition, registerRoot } from "remotion";
import { Root } from "${rootSrcPath}";

// AUTO-GENERATED by \`vf studio\` — regenerated on every launch. Editing
// this file works until the next \`vf studio\`; edit the storyboard instead
// and re-run.

const renderPlan = ${JSON.stringify(renderPlan)};

const App = () => (
  <Composition
    id="video-factory"
    component={Root}
    durationInFrames={renderPlan.totalFrames}
    fps={renderPlan.project.fps}
    width={renderPlan.project.width}
    height={renderPlan.project.height}
    defaultProps={{ renderPlan }}
  />
);

registerRoot(App);
`;

const STUDIO_PACKAGE_JSON = `{
  "name": "vf-studio-workspace",
  "private": true,
  "type": "module"
}
`;

const STUDIO_CONFIG = `import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
`;

const STUDIO_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "strict": true,
    "skipLibCheck": true,
    "noEmit": true
  }
}
`;

/**
 * Generate a self-contained Remotion Studio workspace (plan T0.3) for a
 * project's CURRENT compiled plan. The workspace lives under
 * `packages/video-renderer/.studio/<slug>/` so its imports of `remotion`
 * and `@remotion/cli/config` resolve against this package's node_modules
 * (pnpm does not hoist them to projects/<slug>/). Re-running overwrites
 * the entry with the fresh plan — a running Studio picks the change up.
 */
export async function prepareStudioWorkspace(
  projectRoot: string,
  renderPlan: RenderPlan,
  workspaceDir: string = path.join(
    path.dirname(rendererDir),
    ".studio",
    path.basename(projectRoot) || "project",
  ),
): Promise<StudioWorkspace> {
  const resolvedPlan = await resolveImageSources(renderPlan);
  const srcDir = path.join(workspaceDir, "src");
  await mkdir(srcDir, { recursive: true });
  await writeFile(
    path.join(workspaceDir, "package.json"),
    STUDIO_PACKAGE_JSON,
    "utf8",
  );
  await writeFile(
    path.join(workspaceDir, "remotion.config.ts"),
    STUDIO_CONFIG,
    "utf8",
  );
  // Studio warns (and type-checks poorly) without a tsconfig.
  await writeFile(
    path.join(workspaceDir, "tsconfig.json"),
    STUDIO_TSCONFIG,
    "utf8",
  );
  await writeFile(
    path.join(srcDir, "index.tsx"),
    studioEntryTemplate(resolvedPlan),
    "utf8",
  );
  const localBin = findStudioBin();
  return {
    bin: localBin ?? "remotion",
    cwd: workspaceDir,
    workspaceDir,
  };
}

/** Walk up from this module (which may be src/ under vitest or dist/ when
 * built) to find node_modules/.bin/remotion — @remotion/cli is a
 * dependency of this package. */
function findStudioBin(): string | null {
  let dir = rendererDir;
  for (;;) {
    const candidate = path.join(dir, "node_modules", ".bin", "remotion");
    if (existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
